/**
 * Malaysian name cues and a given-name deny-list.
 *
 * docs/trd.md §9: a gazetteer is the **only** measure available in this window
 * that raises name recall without a model, and the published evidence says an
 * ML NER would miss unmarked Malay names disproportionately anyway. It is a
 * second recall pass for names carrying no particle or honorific cue — not a
 * claim of completeness. docs/prd.md §12 states the recall limitation plainly.
 */

/** Titles that precede a name. Malay, English and clinical. */
export const HONORIFICS = [
  'Mr',
  'Mrs',
  'Ms',
  'Miss',
  'Dr',
  'Prof',
  'Encik',
  'Cik',
  'Puan',
  'Tuan',
  'Datuk',
  'Dato',
  'Datin',
  'Tan Sri',
  'Haji',
  'Hajjah',
] as const

/**
 * Patronymic and filial particles. These sit *between* name parts, so a match
 * extends the span in both directions — `Ahmad bin Ismail` is one name, not two.
 */
export const PATRONYMICS = ['bin', 'binti', 'bt', 'bte', 'a/l', 'a/p', 'anak'] as const

/** Phrases after which the next capitalised run is a name. */
export const NAME_INTRODUCERS = [
  'my name is',
  'name is',
  "patient's name is",
  'patient name',
  'nama saya',
  'saya',
  'this is',
  'i am',
] as const

/**
 * Given names common in Malaysia across the three main communities. Deliberately
 * a *given*-name list: surnames and second elements are picked up by the
 * adjacency rules, and a longer list would trade precision for little recall.
 */
export const GIVEN_NAMES = new Set(
  [
    // Malay
    'ahmad',
    'muhammad',
    'mohd',
    'mohamad',
    'mohamed',
    'abdul',
    'abdullah',
    'ali',
    'ismail',
    'ibrahim',
    'hassan',
    'hussein',
    'osman',
    'razak',
    'rahim',
    'aziz',
    'farid',
    'faizal',
    'hakim',
    'iskandar',
    'khairul',
    'nazri',
    'rizal',
    'syafiq',
    'zainal',
    'zulkifli',
    'amir',
    'danial',
    'haziq',
    'irfan',
    'siti',
    'nur',
    'nurul',
    'aisyah',
    'fatimah',
    'hasnah',
    'khadijah',
    'maimunah',
    'noraini',
    'rohana',
    'salmah',
    'zainab',
    'zuraida',
    'aminah',
    'halimah',
    'sharifah',
    'wan',
    'nabila',
    'syafiqah',
    'aleeya',
    'balqis',
    // Chinese
    'tan',
    'lim',
    'lee',
    'wong',
    'chan',
    'cheah',
    'chong',
    'chew',
    'goh',
    'khoo',
    'kong',
    'lau',
    'leong',
    'liew',
    'loh',
    'low',
    'ng',
    'ong',
    'sim',
    'teoh',
    'toh',
    'yap',
    'yeo',
    'yong',
    'chin',
    'foo',
    'ho',
    'kang',
    'koh',
    'lai',
    'wei',
    'ming',
    'hui',
    'jia',
    'xin',
    'yi',
    'ling',
    'mei',
    'siew',
    'chee',
    // Indian
    'arumugam',
    'balakrishnan',
    'chandran',
    'ganesan',
    'gopal',
    'krishnan',
    'kumar',
    'kumaran',
    'maniam',
    'muniandy',
    'murugan',
    'nadarajah',
    'raj',
    'rajan',
    'ramasamy',
    'ravi',
    'samy',
    'selvam',
    'subramaniam',
    'suresh',
    'thanaraj',
    'vellu',
    'devi',
    'kaur',
    'lakshmi',
    'priya',
    'shanti',
    'usha',
    'singh',
    'anand',
    'deepa',
    'kavitha',
    'meena',
    'nithya',
  ].map((n) => n.toLowerCase()),
)

/**
 * Words that look like names by shape but are clinical, geographic or
 * conversational. Without this the detector tokenises half the transcript,
 * which destroys the note rather than protecting it.
 */
export const NAME_STOPWORDS = new Set(
  [
    'doctor',
    'patient',
    'clinic',
    'hospital',
    'panel',
    'pharmacy',
    'nurse',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
    'january',
    'february',
    'march',
    'april',
    'may',
    'june',
    'july',
    'august',
    'september',
    'october',
    'november',
    'december',
    'paracetamol',
    'amoxicillin',
    'ibuprofen',
    'lozenge',
    'antibiotic',
    'antibiotics',
    'covid',
    'influenza',
    'urti',
    'mc',
    'ic',
    'nric',
    'mykad',
    'rm',
    'yes',
    'no',
    'ok',
    'okay',
    'sorry',
    'thanks',
    'thank',
    'please',
    'hello',
    'good',
    'morning',
    'afternoon',
    'evening',
    'night',
    'today',
    'yesterday',
    'tomorrow',
    'week',
    'day',
    'days',
    'month',
    'year',
    'i',
    'you',
    'he',
    'she',
    'it',
    'we',
    'they',
    'the',
    'and',
    'but',
    'so',
    'my',
    'your',
    'his',
    'her',
    'their',
    'this',
    'that',
    'have',
    'has',
    'had',
    // Malay everyday words. Load-bearing against the bare 'saya' introducer:
    // without these, "...untuk saya Doktor" mints a false PATIENT token, and a
    // false token corrupts the note on rehydration. Deliberately absent
    // although they are months or weekdays: 'mei' (a given name in
    // GIVEN_NAMES) and 'khamis', 'jumaat', 'sabtu', 'ahad' (attested Malay
    // given names outside the gazetteer, where trimNameSpan's stopword loop
    // would strip them off a patronymic span and leak them in cleartext).
    // A recall loss on the PHI boundary outranks the precision gain.
    'doktor',
    'klinik',
    'jururawat',
    'ubat',
    'sakit',
    'demam',
    'batuk',
    'selsema',
    'pesakit',
    'farmasi',
    'isnin',
    'selasa',
    'rabu',
    'januari',
    'februari',
    'mac',
    'jun',
    'julai',
    'ogos',
    'oktober',
    'disember',
    'malaysia',
    'selangor',
    'johor',
    'penang',
    'sabah',
    'sarawak',
    'perak',
    'kedah',
    'kelantan',
    'melaka',
    'pahang',
    'perlis',
    'terengganu',
    'kuala',
    'lumpur',
    'putrajaya',
    'labuan',
    'shah',
    'alam',
    'petaling',
    'jaya',
  ].map((w) => w.toLowerCase()),
)
